openapi: 3.0.1
info:
  title: Sync Worker
  description: basic template for map colonies service
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

paths:
  /tilesCount/{jobId}:
    get:
      operationId: getTilesCount
      tags:
        - tiles
      summary: gets the tiles count by job id
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTilesCount'
    put:
      operationId: updateTilesCount
      tags:
        - tiles
      summary: updates the tiles count by job id
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updateTilesCount'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    getTilesCount:
      type: object
      required:
        - tilesCount
      properties:
        tilesCount:
          type: number
    updateTilesCount:
      type: object
      required:
        - message
      properties:
        message:
          type: string
