{{- if and .Values.authentication.ca.enabled (not .Values.authentication.ca.useExternal) -}}
{{ $caPath := .Values.local.certs.ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-root-ca
type: Opaque
stringData:
  {{- if $caPath }}
  caFile: {{ .Files.Get $caPath | quote }}
  {{- end }}
{{- end }}
