{{- $releaseName := .Release.Name -}}
{{- $chartName := include "sync-worker.name" . -}}
{{- $cloudProviderFlavor := include "sync-worker.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "sync-worker.cloudProviderDockerRegistryUrl" . -}}
{{- $imageTag := include "sync-worker.tag" . -}}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "sync-worker.environment" . }}
    release: {{ $releaseName }}
    {{- include "sync-worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
      {{- include "sync-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
        {{- include "sync-worker.selectorLabels" . | nindent 8 }}
    spec:
    {{- if .Values.cloudProvider.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.cloudProvider.imagePullSecretName | quote }}
    {{- end }}
    {{- if or (eq (upper .Values.env.storageProvider) "FS") .Values.env.tiles.sigIsNeeded }}
      volumes:
    {{- if eq (upper .Values.env.storageProvider) "FS" }}
      - name: sources-storage
        persistentVolumeClaim:
          claimName: {{ .Values.storage.internalPvc.name }}
    {{- end }}
    {{- if .Values.env.tiles.sigIsNeeded }}
      - name: key-file
        configMap:
          name: {{ .Release.Name }}-{{ $chartName }}-configmap
          items:
          - key: "PRIVATE_KEY"
            path: "private_key.pem"
    {{- end }}
    {{- end }}
      containers:
        - name: {{ $releaseName }}-{{ $chartName }}-deployment
          {{- with .Values.image }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ $imageTag }}
          {{- end }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.env.targetPort | quote }}
            {{- if eq (upper .Values.env.storageProvider) "S3" }}
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.S3.secret.name }}
                  key: accessKeyId
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.S3.secret.name }}
                  key: secretAccessKey
            {{- end }}
            - name: CRYPTO_PEM
              value: "/usr/src/app/private_key.pem"
          envFrom:
            - configMapRef:
                name: {{ $releaseName }}-{{ $chartName }}-configmap
          ports:
            - name: http
              containerPort: {{ .Values.env.targetPort }}
              protocol: {{ .Values.env.protocol }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /liveness
              port: http
          {{- if or (eq (upper .Values.env.storageProvider) "FS") .Values.env.tiles.sigIsNeeded }}
          volumeMounts: 
          {{- if eq (upper .Values.env.storageProvider) "FS" }}
            - name: sources-storage
              mountPath: {{ .Values.storage.internalPvc.mountPath }}
              subPath: tiles
          {{- end }}
          {{- if .Values.env.tiles.sigIsNeeded }}
            - mountPath: "/usr/src/app/private_key.pem"
              name: key-file
              subPath: private_key.pem
          {{- end }}
          {{- end }}
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
{{- end -}}
