{{- if .Values.gateway.secret.create -}}
{{- if or (.Values.env.gateway.auth.enabled) (.Values.env.tiles.sigIsNeeded) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gateway.secret.name }}
type: Opaque
{{- if .Values.env.gateway.auth.enabled }}
stringData:
  username: {{ quote .Values.env.gateway.auth.username }}
  password: {{ quote .Values.env.gateway.auth.password }}
{{- end }}
{{- if .Values.env.tiles.sigIsNeeded }}
data:
  {{ $globdata := .Files.Glob .Values.env.crypto.pem }}
  {{ if $globdata }}
  PRIVATE_KEY: {{ .Files.Get .Values.env.crypto.pem | b64enc }}
  {{ else }}
  {{- fail  (printf "Key file not found at path: %s" .Values.env.crypto.pem) }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
