{{- if and .Values.authentication.ssl.enabled (not .Values.authentication.ssl.useExternal) -}}
{{ $sslPath := .Values.local.certs.ssl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-open-ssl
type: Opaque
data:
  openssl.cnf: {{ .Files.Get $sslPath | b64enc }}
{{- end }}
