global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
environment: "development"
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30030 #for minikube deployment only

cloudProvider:
  dockerRegistryUrl: "my-registry"
  flavor: "azure"

image:
  repository: "sync-worker"
  tag: "latest"

storage:
  internalPvc:
    create: false
    name: "internal-pvc"
    mountPath: "/layerSources"
  internalPv:
    name: "internal-pv"
    directory: "/layerSources"

env:
  port: 8089
  targetPort: 8089
  protocol: TCP
  logLevel: debug
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: "http://localhost:55681/v1/trace"
  metrics:
    enabled: false
    url: "http://localhost:55681/v1/metrics"
  layerSpecBaseUrl: "http://localhost:8080"
  nifiBaseUrl: "http://localhost:8083"
  syncAttempts: 3
  gatewayUrl: "http://localhost:8084"
  gatewayRouteId: ""
  tiles:
    path: /layerSources
    format: png
    uploadBatchSize: 100
    sigIsNeeded: false
  crypto:
    readFileEncoding: ""
    pem: ""
    algoritm: ""
    shaSize: ""
  queue:
    jobManagerBaseUrl: "http://localhost:8082"
    heartbeatManagerBaseUrl: "http://localhost:8085"
    dequeueIntervalMs: 3
    heartbeatIntervalMs: 0.5
    jobType: "Sync"
    taskType: "Sync"
resources:
  enabled: false
  value:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"

